application:
  max-allowed-books: 5
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: example
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true