# Use root/example as user/password credentials

version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /home/leniv/Documents/GB/java_spring/seminar_3/db:/var/lib/mysql
    ports:
      - 3306:3306
